---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title: "Johannes Ulén"
description: "Personal homepage"
baseurl: ""
url: http://johannesu.github.io
favicon:     "img/favicon.ico"
google_analytics_key:


### template colors, used site-wide via css ###
colors:
  lightgray: '#e5e5e5'
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#97add2'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#ffd99c'
  turquoise: '#93e1bf'

kramdown:
  auto_ids:  false

